apiVersion: batch/v1
kind: Job
metadata:
  name: trainer
  namespace: default
spec:
  ttlSecondsAfterFinished: 360
  template:
    metadata:
      labels:
        app: trainer
    spec:
      restartPolicy: Never
      containers:
        - name: trainer
          image: esadik/ai-trainer:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data
              name: training-data
      volumes:
        - name: training-data
          persistentVolumeClaim:
            claimName: ai-data-pvc
